name: Pantheon WordPress Upstream Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1-5"

jobs:
  sync:
    name: Sync upstream
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Add the safe directory configuration directly using 'run'
    - name: Mark repository as safe
      run: git config --global --add safe.directory /github/workspace
    
    - name: git remote
      uses: srt32/git-actions@v0.0.3
      with:
        args: git remote add upstream https://github.com/pantheon-systems/WordPress.git && git fetch upstream
    
    - name: git config
      uses: srt32/git-actions@v0.0.3
      with:
        args: git config --global user.email "erik.mitchell@boomi.com"; git config --global user.name "Erik Mitchell" 
    
    - name: git merge
      uses: srt32/git-actions@v0.0.3
      with:
        args: git checkout --track origin/master && git rebase upstream/master master --no-commit && git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY} -f
